#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  printf "COMMIT SUCCEEDED\n"
  exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES; do
  goimports -w $FILE
done

go vet
if [[ $? != 0 ]]; then
  PASS=false
fi

gosec ./...
if [[ $? != 0 ]]; then
  PASS=false
fi

if ! $PASS; then
  printf "COMMIT FAILED\n"
  exit 1
else
  printf "COMMIT SUCCEEDED\n"
fi

exit 0