#!/bin/sh

STAGED_GO_FILES=$(git diff --cached --name-only | grep ".go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  exit 0
fi

PASS=true

for FILE in $STAGED_GO_FILES; do

  goimports -w $FILE

  golint "-set_exit_status" $FILE
  if [[ $? == 1 ]]; then
    PASS=false
  fi
  echo "golint executed successfully"
  
  go vet $FILE
  if [[ $? != 0 ]]; then
    PASS=false
  fi
  echo "go vet executed successfully"

done

if ! $PASS; then
  echo "COMMIT FAILED"
  exit 1
else
  echo "COMMIT SUCCEEDED"
fi

exit 0